// src/redux/types.ts

// 🏨 ROOM ACTION TYPES
export const FETCH_ROOM_CATEGORIES_REQUEST = "FETCH_ROOM_CATEGORIES_REQUEST";
export const FETCH_ROOM_CATEGORIES_SUCCESS = "FETCH_ROOM_CATEGORIES_SUCCESS";
export const FETCH_ROOM_CATEGORIES_FAILURE = "FETCH_ROOM_CATEGORIES_FAILURE";

export const FETCH_ROOMS_REQUEST = "FETCH_ROOMS_REQUEST";
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS";
export const FETCH_ROOMS_FAILURE = "FETCH_ROOMS_FAILURE";

export const FETCH_ROOM_DETAILS_REQUEST = "FETCH_ROOM_DETAILS_REQUEST";
export const FETCH_ROOM_DETAILS_SUCCESS = "FETCH_ROOM_DETAILS_SUCCESS";
export const FETCH_ROOM_DETAILS_FAILURE = "FETCH_ROOM_DETAILS_FAILURE";

// 📝 RESERVATION / BOOKING ACTION TYPES
export const CHECK_AVAILABILITY_REQUEST = "CHECK_AVAILABILITY_REQUEST";
export const CHECK_AVAILABILITY_SUCCESS = "CHECK_AVAILABILITY_SUCCESS";
export const CHECK_AVAILABILITY_FAILURE = "CHECK_AVAILABILITY_FAILURE";

export const CREATE_RESERVATION_REQUEST = "CREATE_RESERVATION_REQUEST";
export const CREATE_RESERVATION_SUCCESS = "CREATE_RESERVATION_SUCCESS";
export const CREATE_RESERVATION_FAILURE = "CREATE_RESERVATION_FAILURE";

export const TRACK_RESERVATION_REQUEST = "TRACK_RESERVATION_REQUEST";
export const TRACK_RESERVATION_SUCCESS = "TRACK_RESERVATION_SUCCESS";
export const TRACK_RESERVATION_FAILURE = "TRACK_RESERVATION_FAILURE";

export const CLEAR_RESERVATION_STATE = "CLEAR_RESERVATION_STATE";
